config/routes.rb
Uploader::Application.routes.draw do
  resources :users
  
  resources :galleries

  get "users/galleries/:id" => "users#galleries", :as => :users_galleries
  post "galleries/photo" => 'galleries#photo'
  root :to => 'users#index'
  match "/images/uploads/*path" => "galleries#serve"

end

app/models/gallery.rb
class Gallery
  include Mongoid::Document
  field :user_id, :type => String
  field :title, :type => String
  mount_uploader :photo, PhotoUploader
  belongs_to :user
end

app/models/user.rb
class User
  include Mongoid::Document
  field :name, :type => String
  field :password, :type => String
  field :email, :type => String
  has_many :galleries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery  :except => :photo
end

app/controllers/galleries_controller.rb
require 'mongo'
class GalleriesController < ApplicationController
  # GET /galleries
  # GET /galleries.json
  def index
    if params[:user_id]
      @galleries = Gallery.where("user_id" => params[:user_id] );
    else
      @galleries = Gallery.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/new
  # GET /galleries/new.json
  def new
    @gallery = Gallery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(params[:gallery])

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render json: @gallery, status: :created, location: @gallery }
      else
        format.html { render action: "new" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end

  def serve
    gridfs_path = env["PATH_INFO"].gsub("/images/", "")

    begin
      gridfs_file = Mongo::GridFileSystem.new(Mongoid.database).open(gridfs_path, 'r')
      self.response_body = gridfs_file.read
      self.content_type = gridfs_file.content_type
    rescue
      self.status = :file_not_found
      self.content_type = 'text/plain'
      self.response_body = ''
    end
  end

  def photo
    @gallery = Gallery.new(:title => params[:title], :photo => params[:photo], :user_id => params[:user_id] )

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render json: @gallery, status: :created, location: @gallery }
      else
        format.html { render action: "new" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /user/1/galleries
  # GET /user/1/galleries.json
  def galleries
    @user = User.where("id" => :id);
    @galleries = Gallery.where("user_id" => :id);

    respond_to do |format|
      format.html
      format.json { render json: @galleries }
    end
  end


  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/galleries/_form.html.erb
<%= form_for [@user, @gallery] do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= image_tag( @gallery.photo_url ) if @gallery.photo? %>
    <%= f.file_field :photo %>
    <%= f.hidden_field :photo_cache %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>作品編集</h1>

<div class="frame">

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

</div>

app/views/galleries/index.html.erb
<h1>作品一覧</h1>

<p class="line" />

<div class="frame">

<table>
  <tr>
    <th class="box">Title</th>
    <th class="box">Photo</th>
    <th colspan="3" class="box"></th>
  </tr>

<% @galleries.each do |gallery| %>
  <tr class="backColor">
    <td class="box"><%= gallery.title %></td>
    <td class="box"><%= image_tag(gallery.photo_url(:thumb).to_s) if gallery.photo? %></td>
    <td class="box"><%= link_to 'Show', gallery %></td>
    <td class="box"><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
    <td class="box"><%= link_to 'Destroy', gallery, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gallery', new_gallery_path %>
<%= link_to 'Go To Index', users_path %>

</div>

app/views/galleries/new.html.erb
<h1>作品登録</h1>

<div class="frame">

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

</div>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<div class="frame">

<p>
  <b>Title:</b>
  <%= @gallery.title %>
</p>

<p>
  <b>Photo:</b>
  <%= image_tag(@gallery.photo_url) if @gallery.photo? %>
</p>

<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uploader</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザ編集</h1>

<div class="frame">
<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
</div>

app/views/users/galleries.html.erb
<h1>Listing galleries</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Photo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @galleries.each do |gallery| %>
  <tr>
    <td><%= gallery.title %></td>
    <td><%= image_tag(gallery.photo_url(:thumb).to_s) if gallery.photo? %></td>
    <td><%= link_to 'Show', gallery %></td>
    <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
    <td><%= link_to 'Destroy', gallery, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gallery', new_user_gallery_path %>

app/views/users/index.html.erb
<h1>ユーザ一覧</h1>

<p class="line"></p>

<div class="frame">

<table>
  <tr class="titleColor">
    <th class="box">Name</th>
    <th class="box">Email</th>
    <th colspan="4" class="box"></th>
  </tr>

<% @users.each do |user| %>
  <tr class="backColor">
    <td class="box"><%= user.name %></td>
    <td class="box"><%= user.email %></td>
    <td class="box"><%= link_to 'Galleries', galleries_path(:user_id => user.id) %></td>
    <td class="box"><%= link_to 'Show', user %></td>
    <td class="box"><%= link_to 'Edit', edit_user_path(user) %></td>
    <td class="box"><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

</div>

app/views/users/new.html.erb
<h1>ユーザ作成</h1>

<div class="frame">
<%= render 'form' %>

<%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="frame">

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

</div>